show databases;

CREATE DATABASE PROJETO;
USE PROJETO;

CREATE TABLE CARROS(
	IDCARRO INT,
	MODELO VARCHAR(30) NOT NULL,
    ID_MARCA VARCHAR(20) NOT NULL UNIQUE,
    ID_CLIENTE INT UNIQUE
);

CREATE TABLE CLIENTE(
	IDCLIENTE INT,
    NOME VARCHAR(20) NOT NULL,
    SEXO CHAR(1)
);

CREATE TABLE CORES(
	IDCOR INT,
	COR VARCHAR(15) NOT NULL,
    ID_CARRO INT
);

CREATE TABLE TELEFONE(
	IDTELEFONE CHAR(3) #***
	NUMERO VARCHAR(11),
    ID_CLIENTE INT
);